### ISSUE TITLE
update dfd 

### ISSUE THREAD

**Issue by ginnjy** [scaryoke/ISQA-3420#8]
change corporate manger to corporate project auditor.

**Comment by thinlionbirdflu** [comment]
Germonprez has a list of other processes that are in the slides. This is something we will need to expand on in our DFD.

**Comment by thinlionbirdflu** [comment]
![oss dfd](https://cloud.githubusercontent.com/assets/14796049/11192625/bbbb911c-8c67-11e5-8876-9ddfd373de01.png)

**Comment by thinlionbirdflu** [comment]
This issue will be ongoing, but we will open a new issue to track updates needed based on inclass exercises.
